# This is a sample build configuration for C++ – Make.
# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
image: gcc:6.1
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
          - apt-get install -y -q libc6-dev
          - cd firmware
          - export PATH=$GCC_DIR/bin:$PATH
          - echo $PATH
          - git submodule init
          - git submodule update
          - make bin